export default StaticImages = {
  appication: {
    logo: require('../assets/images/xarraf-logo.png'),
    logo_white: require('../assets/images/xarraf-logo-white.png'),
  },
  langImages: {
    en: require('../assets/images/flags/en.png'),
    fr: require('../assets/images/flags/fr.png'),
    de: require('../assets/images/flags/de.png'),
    es: require('../assets/images/flags/es.png'),
    ru: require('../assets/images/flags/ru.png'),
    tr: require('../assets/images/flags/tr.png'),
    ar: require('../assets/images/flags/ar.png'),
    uk: require('../assets/images/flags/uk.png'),
  },
  counriesFlag: {
    aw: require('../assets/images/flags/aw.png'),
    af: require('../assets/images/flags/af.png'),
    ao: require('../assets/images/flags/ao.png'),
    ai: require('../assets/images/flags/ai.png'),
    ax: require('../assets/images/flags/ax.png'),
    al: require('../assets/images/flags/al.png'),
    ad: require('../assets/images/flags/ad.png'),
    ae: require('../assets/images/flags/ae.png'),
    ar: require('../assets/images/flags/ar.png'),
    am: require('../assets/images/flags/am.png'),
    as: require('../assets/images/flags/as.png'),
    aq: require('../assets/images/flags/aq.png'),
    tf: require('../assets/images/flags/tf.png'),
    au: require('../assets/images/flags/au.png'),
    at: require('../assets/images/flags/at.png'),
    az: require('../assets/images/flags/az.png'),
    bi: require('../assets/images/flags/bi.png'),
    be: require('../assets/images/flags/be.png'),
    bj: require('../assets/images/flags/bj.png'),
    bf: require('../assets/images/flags/bf.png'),
    bd: require('../assets/images/flags/bd.png'),
    bg: require('../assets/images/flags/bg.png'),
    bh: require('../assets/images/flags/bh.png'),
    bs: require('../assets/images/flags/bs.png'),
    by: require('../assets/images/flags/by.png'),
    bz: require('../assets/images/flags/bz.png'),
    bm: require('../assets/images/flags/bm.png'),
    bo: require('../assets/images/flags/bo.png'),
    br: require('../assets/images/flags/br.png'),
    bb: require('../assets/images/flags/bb.png'),
    bn: require('../assets/images/flags/bn.png'),
    bt: require('../assets/images/flags/bt.png'),
    bv: require('../assets/images/flags/bv.png'),
    bw: require('../assets/images/flags/bw.png'),
    cf: require('../assets/images/flags/cf.png'),
    ca: require('../assets/images/flags/ca.png'),
    cc: require('../assets/images/flags/cc.png'),
    ch: require('../assets/images/flags/ch.png'),
    cl: require('../assets/images/flags/cl.png'),
    cn: require('../assets/images/flags/cn.png'),

    cm: require('../assets/images/flags/cm.png'),

    ck: require('../assets/images/flags/ck.png'),
    co: require('../assets/images/flags/co.png'),
    km: require('../assets/images/flags/km.png'),
    cv: require('../assets/images/flags/cv.png'),
    cr: require('../assets/images/flags/cr.png'),
    cu: require('../assets/images/flags/cu.png'),
    cw: require('../assets/images/flags/cw.png'),
    cx: require('../assets/images/flags/cx.png'),
    ky: require('../assets/images/flags/ky.png'),
    cy: require('../assets/images/flags/cy.png'),

    de: require('../assets/images/flags/de.png'),
    dj: require('../assets/images/flags/dj.png'),
    dm: require('../assets/images/flags/dm.png'),
    dk: require('../assets/images/flags/dk.png'),
    do: require('../assets/images/flags/do.png'),
    dz: require('../assets/images/flags/dz.png'),
    ec: require('../assets/images/flags/ec.png'),
    eg: require('../assets/images/flags/eg.png'),
    er: require('../assets/images/flags/er.png'),
    eh: require('../assets/images/flags/eh.png'),
    es: require('../assets/images/flags/es.png'),
    ee: require('../assets/images/flags/ee.png'),
    et: require('../assets/images/flags/et.png'),
    fi: require('../assets/images/flags/fi.png'),
    fj: require('../assets/images/flags/fj.png'),
    fk: require('../assets/images/flags/fk.png'),
    fr: require('../assets/images/flags/fr.png'),
    fo: require('../assets/images/flags/fo.png'),
    fm: require('../assets/images/flags/fm.png'),
    ga: require('../assets/images/flags/ga.png'),
    gb: require('../assets/images/flags/gb.png'),
    ge: require('../assets/images/flags/ge.png'),
    gg: require('../assets/images/flags/gg.png'),
    gh: require('../assets/images/flags/gh.png'),
    gi: require('../assets/images/flags/gi.png'),
    gn: require('../assets/images/flags/gn.png'),
    gp: require('../assets/images/flags/gp.png'),
    gm: require('../assets/images/flags/gm.png'),

    gq: require('../assets/images/flags/gq.png'),
    gr: require('../assets/images/flags/gr.png'),
    gd: require('../assets/images/flags/gd.png'),
    gl: require('../assets/images/flags/gl.png'),
    gt: require('../assets/images/flags/gt.png'),
    gf: require('../assets/images/flags/gf.png'),
    gu: require('../assets/images/flags/gu.png'),
    gy: require('../assets/images/flags/gy.png'),

    hn: require('../assets/images/flags/hn.png'),
    hr: require('../assets/images/flags/hr.png'),
    ht: require('../assets/images/flags/ht.png'),
    hu: require('../assets/images/flags/hu.png'),
    id: require('../assets/images/flags/id.png'),

    in: require('../assets/images/flags/in.png'),
    io: require('../assets/images/flags/io.png'),
    ie: require('../assets/images/flags/ie.png'),
    ir: require('../assets/images/flags/ir.png'),
    iq: require('../assets/images/flags/iq.png'),
    is: require('../assets/images/flags/is.png'),
    il: require('../assets/images/flags/il.png'),
    it: require('../assets/images/flags/it.png'),
    jm: require('../assets/images/flags/jm.png'),
    je: require('../assets/images/flags/je.png'),
    jo: require('../assets/images/flags/jo.png'),
    jp: require('../assets/images/flags/jp.png'),
    kz: require('../assets/images/flags/kz.png'),
    ke: require('../assets/images/flags/ke.png'),
    kg: require('../assets/images/flags/kg.png'),
    kh: require('../assets/images/flags/kh.png'),
    ki: require('../assets/images/flags/ki.png'),

    kr: require('../assets/images/flags/kr.png'),
    kw: require('../assets/images/flags/kw.png'),
    la: require('../assets/images/flags/la.png'),
    lb: require('../assets/images/flags/lb.png'),
    lr: require('../assets/images/flags/lr.png'),
    ly: require('../assets/images/flags/ly.png'),

    li: require('../assets/images/flags/li.png'),
    lk: require('../assets/images/flags/lk.png'),
    ls: require('../assets/images/flags/ls.png'),
    lt: require('../assets/images/flags/lt.png'),
    lu: require('../assets/images/flags/lu.png'),
    lv: require('../assets/images/flags/lv.png'),

    ma: require('../assets/images/flags/ma.png'),
    mc: require('../assets/images/flags/mc.png'),
    md: require('../assets/images/flags/md.png'),
    mg: require('../assets/images/flags/mg.png'),
    mv: require('../assets/images/flags/mv.png'),
    mx: require('../assets/images/flags/mx.png'),
    mh: require('../assets/images/flags/mh.png'),
    mk: require('../assets/images/flags/mk.png'),
    ml: require('../assets/images/flags/ml.png'),
    mt: require('../assets/images/flags/mt.png'),
    mm: require('../assets/images/flags/mm.png'),
    me: require('../assets/images/flags/me.png'),
    mn: require('../assets/images/flags/mn.png'),
    mp: require('../assets/images/flags/mp.png'),
    mz: require('../assets/images/flags/mz.png'),
    mr: require('../assets/images/flags/mr.png'),
    ms: require('../assets/images/flags/ms.png'),
    mq: require('../assets/images/flags/mq.png'),
    mu: require('../assets/images/flags/mu.png'),
    mw: require('../assets/images/flags/mw.png'),
    my: require('../assets/images/flags/my.png'),
    yt: require('../assets/images/flags/yt.png'),
    na: require('../assets/images/flags/na.png'),
    nc: require('../assets/images/flags/nc.png'),
    ne: require('../assets/images/flags/ne.png'),
    nf: require('../assets/images/flags/nf.png'),
    ng: require('../assets/images/flags/ng.png'),
    ni: require('../assets/images/flags/ni.png'),
    nu: require('../assets/images/flags/nu.png'),
    nl: require('../assets/images/flags/nl.png'),
    no: require('../assets/images/flags/no.png'),
    np: require('../assets/images/flags/np.png'),
    nr: require('../assets/images/flags/nr.png'),
    nz: require('../assets/images/flags/nz.png'),
    om: require('../assets/images/flags/om.png'),
    pk: require('../assets/images/flags/pk.png'),
    pa: require('../assets/images/flags/pa.png'),

    pe: require('../assets/images/flags/pe.png'),
    ph: require('../assets/images/flags/ph.png'),
    pw: require('../assets/images/flags/pw.png'),
    pg: require('../assets/images/flags/pg.png'),
    pl: require('../assets/images/flags/pl.png'),
    pr: require('../assets/images/flags/pr.png'),
    kp: require('../assets/images/flags/kp.png'),
    pt: require('../assets/images/flags/pt.png'),
    py: require('../assets/images/flags/py.png'),

    pf: require('../assets/images/flags/pf.png'),
    qa: require('../assets/images/flags/qa.png'),
    re: require('../assets/images/flags/re.png'),
    ro: require('../assets/images/flags/ro.png'),
    ru: require('../assets/images/flags/ru.png'),
    rw: require('../assets/images/flags/rw.png'),
    sa: require('../assets/images/flags/sa.png'),
    sd: require('../assets/images/flags/sd.png'),
    sn: require('../assets/images/flags/sn.png'),
    sg: require('../assets/images/flags/sg.png'),

    sb: require('../assets/images/flags/sb.png'),
    sl: require('../assets/images/flags/sl.png'),
    sv: require('../assets/images/flags/sv.png'),
    sm: require('../assets/images/flags/sm.png'),
    so: require('../assets/images/flags/so.png'),

    rs: require('../assets/images/flags/rs.png'),
    ss: require('../assets/images/flags/ss.png'),

    sr: require('../assets/images/flags/sr.png'),
    sk: require('../assets/images/flags/sk.png'),
    si: require('../assets/images/flags/si.png'),
    se: require('../assets/images/flags/se.png'),
    sz: require('../assets/images/flags/sz.png'),
    sx: require('../assets/images/flags/sx.png'),
    sc: require('../assets/images/flags/sc.png'),
    sy: require('../assets/images/flags/sy.png'),

    td: require('../assets/images/flags/td.png'),
    tg: require('../assets/images/flags/tg.png'),
    th: require('../assets/images/flags/th.png'),
    tj: require('../assets/images/flags/tj.png'),
    tk: require('../assets/images/flags/tk.png'),
    tm: require('../assets/images/flags/tm.png'),

    to: require('../assets/images/flags/to.png'),

    tn: require('../assets/images/flags/tn.png'),
    tr: require('../assets/images/flags/tr.png'),
    tv: require('../assets/images/flags/tv.png'),
    tw: require('../assets/images/flags/tw.png'),
    tz: require('../assets/images/flags/tz.png'),
    ug: require('../assets/images/flags/ug.png'),
    ua: require('../assets/images/flags/ua.png'),

    uy: require('../assets/images/flags/uy.png'),
    us: require('../assets/images/flags/us.png'),
    uz: require('../assets/images/flags/uz.png'),

    ve: require('../assets/images/flags/ve.png'),
    vg: require('../assets/images/flags/vg.png'),

    vn: require('../assets/images/flags/vn.png'),
    vu: require('../assets/images/flags/vu.png'),

    ws: require('../assets/images/flags/ws.png'),
    ye: require('../assets/images/flags/ye.png'),
    za: require('../assets/images/flags/za.png'),
    zm: require('../assets/images/flags/zm.png'),
    zw: require('../assets/images/flags/zw.png'),
  },
};
